### ISSUE TITLE
NameError: name 'coinOrderQty' is not defined

### ISSUE THREAD

**Issue by pablocusatti** [fj317/PumpBot#124]
Im not soft developer, i made works this bot on oracle vps, but whn i set de btc pair and press enter, the bot makes the buy order successfully, but next this happen:

Coin pair: nxs
Waiting for coin to buy...
Traceback (most recent call last):
  File "PumpBot.py", line 294, in <module>
    message = message.format(coinOrderQty,tradedCoin,coinPriceBought,quotedCoin)
NameError: name 'coinOrderQty' is not defined

**Comment by pablocusatti** [comment]
Coin pair: axs
Waiting for coin to buy...
Traceback (most recent call last):
  File ".\PumpBot.py", line 294, in <module>
    message = message.format(coinOrderQty,tradedCoin,coinPriceBought,quotedCoin)
NameError: name 'coinOrderQty' is not defined

**Comment by mfalconiii** [comment]
Same here! Any idea?

**Comment by pablocusatti** [comment]
I disable this bot until solve

**Comment by BruceGrove92** [comment]
Same error for me

**Comment by leonardobuffoni** [comment]
Some for me

**Comment by idan1210** [comment]
same error for me. please give a idea to fix it
