### ISSUE TITLE
MIN_NOTIONAL - Doesn't place sell order

### ISSUE THREAD

**Issue by LUVhaxo** [fj317/PumpBot#13]
C:\Pumping\PumpBot-master>python PumpBot.py
 ___                                ___           _
(  _`\                             (  _`\        ( )_
| |_) ) _   _   ___ ___   _ _      | (_) )   _   | ,_)
| ,__/'( ) ( )/' _ ` _ `\( '_`\    |  _ <' /'_`\ | |
| |    | (_) || ( ) ( ) || (_) )   | (_) )( (_) )| |_
(_)    `\___/'(_) (_) (_)| ,__/'   (____/'`\___/'`\__)
                         | |
                         (_)
Coin pair: mda
Buy order has been made!
Traceback (most recent call last):
  File "PumpBot.py", line 88, in <module>
    stopLimitTimeInForce = TIME_IN_FORCE_GTC
  File "C:\Users\ahruj\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\client.py", line 1456, in create_oco_order
    return self._post('order/oco', True, data=params)
  File "C:\Users\ahruj\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\client.py", line 240, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "C:\Users\ahruj\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\ahruj\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\client.py", line 197, in _request
    return self._handle_response()
  File "C:\Users\ahruj\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1013): Filter failure: MIN_NOTIONAL

    "buyLimit": 0,
    "profitMargin": 150,
    "percentOfWallet": 6,
    "stopLoss": 0.80,
    "coinPair": "BTC"

It places the buy order but then I get an error before it can sell and I have to sell manually. Why is this?

**Comment by fj317** [comment]
You are running old code, please update to newest code and try again.
