### ISSUE TITLE
API Exception Error

### ISSUE THREAD

**Issue by LUVhaxo** [fj317/PumpBot#2]
I have everything installed, but when I go to run the PumpBot.py file it gives me this error message:

C:\qawe rfSEf\PumpBot-master>python PumpBot.py
Traceback (most recent call last):
  File "PumpBot.py", line 24, in <module>
    BTCBalance = float(client.get_asset_balance(asset='BTC')['free'])
  File "C:\Users\ahruj\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\client.py", line 1792, in get_asset_balance
    res = self.get_account(**params)
  File "C:\Users\ahruj\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\client.py", line 1767, in get_account
    return self._get('account', True, data=params)
  File "C:\Users\ahruj\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\ahruj\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\ahruj\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\client.py", line 197, in _request
    return self._handle_response()
  File "C:\Users\ahruj\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request was 1000ms ahead of the server's time.

The thing is that it let me run it once without issue and it worked fine but then I closed it and went to try again and was given this error and the .py file closes immediately.

**Comment by skydrow68** [comment]
Run test.py and copy/paste what the terminal write

**Comment by fj317** [comment]
This is happening because your timestamp for you PC is different to that of the server. 
My friend who I designed the bot also had this problem and this is the solution that worked for him (windows solution):
1. Go to control panel.
2. Search for time on search bar.
3. Set time and date.
4. Find set internet time tab.
5. Change settings.
6. Set to time.gov.nst and click update time.

If these steps don't work try restarting your PC and updating again.
Sorry I can't be more help but hopefully this resolves the issue.

**Comment by ducchu68** [comment]
HELP... THX

Traceback (most recent call last):
  File "PumpBot.py", line 39, in <module>
    price = float(client.get_avg_price(symbol=tradingPair)['price'])
AttributeError: 'Client' object has no attribute 'get_avg_price'
