### ISSUE TITLE
Error. Keys.json not found. 

### ISSUE THREAD

**Issue by Wolokal** [fj317/PumpBot#58]
**Describe the bug**

Hello, I all ready install python-binance and use command python PumpBot.py and still showing this
Traceback (most recent call last):
  File "PumpBot.py", line 1, in <module>
    from binance.client import Client
ImportError: No module named binance.client

Next I use command python3 PumpBot.py and show this 
Error. Keys.json not found. 
Remember to rename your keys.json.example to keys.json.

so I go to change keys.json.example to keys.json. and still showing this error by using command with python3 and using python its still Traceback (most recent call last):
  File "PumpBot.py", line 1, in <module>
    from binance.client import Client
ImportError: No module named binance.client

nothing change, what I can do?

**Comment by henyoapps** [comment]
Make sure you install sammchardy's Python Binance API

**Comment by Wolokal** [comment]
I use command on terminal pip install python-binance so I think this is it still nothing change

**Comment by Wolokal** [comment]
and now I install by using command pip install python-binance-API and after python3 PumpBot.py I have this

Traceback (most recent call last):
  File "/home/strzyga/Pulpit/PumpBot-master/PumpBot.py", line 1, in <module>
    from binance.client import Client
ImportError: cannot import name 'Client' from 'binance.client' (/home/strzyga/.local/lib/python3.9/site-packages/binance/client.py)

**Comment by fj317** [comment]
You are not installing the python-binance API correctly. Use [these](https://github.com/sammchardy/python-binance#quick-start) instructions to correctly install the API.

**Comment by fj317** [comment]
Can you give a screenshot of the console output after you've run the install command ? Perhaps the install isn't being completed correctly.

**Comment by Wolokal** [comment]
![picture](https://user-images.githubusercontent.com/79796098/109712956-f0ceca80-7ba0-11eb-8999-96939b426146.png)

**Comment by fj317** [comment]
This is a long shot but, follow the steps [this reply](https://github.com/sammchardy/python-binance/issues/515#issuecomment-629253145) does and see if it fixes it.
I.e. download Visual Studio 20__ installer, then select Desktop Development With C++.

**Comment by Wolokal** [comment]
Nothing change, on this weekend I will change system on Linux Then I will try Run this bot after steps
