### ISSUE TITLE
Min Notional

### ISSUE THREAD

**Issue by Lucasp16** [fj317/PumpBot#7]
___                                ___           _
(  _`\                             (  _`\        ( )_
| |_) ) _   _   ___ ___   _ _      | (_) )   _   | ,_)
| ,__/'( ) ( )/' _ ` _ `\( '_`\    |  _ <' /'_`\ | |
| |    | (_) || ( ) ( ) || (_) )   | (_) )( (_) )| |_
(_)    `\___/'(_) (_) (_)| ,__/'   (____/'`\___/'`\__)
                         | |
                         (_)
Coin pair: mda
Traceback (most recent call last):
  File "PumpBot.py", line 65, in <module>
    price=averagePrice)
  File "C:\Users\lucas_3grx5ol\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\client.py", line 1273, in order_limit_buy
    return self.order_limit(timeInForce=timeInForce, **params)
  File "C:\Users\lucas_3grx5ol\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\client.py", line 1237, in order_limit
    return self.create_order(**params)
  File "C:\Users\lucas_3grx5ol\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\client.py", line 1200, in create_order
    return self._post('order', True, data=params)
  File "C:\Users\lucas_3grx5ol\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\client.py", line 240, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "C:\Users\lucas_3grx5ol\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\lucas_3grx5ol\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\client.py", line 197, in _request
    return self._handle_response()
  File "C:\Users\lucas_3grx5ol\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1013): Filter failure: MIN_NOTIONAL

Everything is installed properly and I have changed the system time. Any help would be greatly appreciated.

**Comment by ArielKatzir** [comment]
Usually, this error comes up if you tried to create a buy order that is lower than the minimum amount required. For the coin MDA, the minimum MDA trading amount is 1MDA and also it has to be more than 0.0001 BTC. Is it possible that your order had a lower value than these two?

**Comment by Lucasp16** [comment]
Yes, that was the case. To test the bot I was running it on 1% account risk so that must have been too little of an amount. When I raised it to 5% I had no issues. Thanks!

**Comment by ducchu68** [comment]
Traceback (most recent call last):
  File "PumpBot.py", line 56, in <module>
    amountOfCoin = BTCtoSell / price;
NameError: name 'price' is not defined

**Comment by fj317** [comment]
> 
> 
> Traceback (most recent call last):
> File "PumpBot.py", line 56, in
> amountOfCoin = BTCtoSell / price;
> NameError: name 'price' is not defined

Please create a new issue for any bugs and do not go off topic in threads. Now locked.
The solution to your problem is I left a semi colon on the end of the line. Delete this and it should work fine again.
